apiVersion: v1
data:
  hazelcast.yaml: |-
    hazelcast:
      cluster-name: hazelcast-cluster
      network:
        join:
          multicast:
            enabled: false
          kubernetes:
            enabled: true
            service-dns: hazelcast-embedded-springboot-service.develop.svc.cluster.local
kind: ConfigMap
metadata:
  name: hazelcast-config
  namespace: develop