apiVersion: v1
kind: Service
metadata:
  name: hazelcast-embedded-springboot-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: hazelcast-embedded-springboot
  ports:
  - name: hazelcast
    port: 5701
