---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-embedded-springboot-service-ingress
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: hazelcast-embedded-springboot
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: hazelcast-embedded-springboot-backend
spec:
  prefix: /hazelcast/
  service: hazelcast-embedded-springboot-service-ingress
